@hostname = localhost
@port = 2001
@url = https://{{hostname}}:{{port}}/api/services/inventory/company
@id = 1


###
# Get All brands
GET {{url}}

###
POST {{url}}
Content-Type: application/json

{
  "name": "Gözen Holding",
  "description": "Holding açýklama",
  "businessCode": 34000
}


### Brand Update
PUT {{url}}/{{id}}
Content-Type: application/json

{
    "id": {{id}}
}



### Brand Delete
DELETE {{url}}/{{id}}

